<?php
global $wpdb;
global $current_user;
get_currentuserinfo();
$userid = $current_user->ID;

if ($userid <> 0)
{
echo "<table width='800' border='0' cellspacing='1' cellpadding='1'>";
echo "<tr>";
echo "<td nowrap width='600'>";

echo "<table border='1' cellspacing='1' cellpadding='1'>";
echo "<tr>";
echo "<th nowrap colspan='5'><h1>Punktestand</h1></th>";
echo "</tr>";
echo "<tr bgcolor='#FF9933'>";
echo "<th nowrap>Platz</th>";
echo "<th nowrap>Name</th>";
echo "<th nowrap>Weltmeistertipp</th>";
echo "<th nowrap>5 €</th>";
echo "<th nowrap>Punktestand</th>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFEFAF'>1</td>";
echo "<td nowrap STYLE='background-color:#FFEFAF'>Eugen</td>";
echo "<td nowrap STYLE='background-color:#FFEFAF'>Niederlande</td>";
echo "<td nowrap STYLE='background-color:#FFEFAF'>-</td>";
echo "<td nowrap STYLE='background-color:#FFEFAF'>43</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF9C4'>2</td>";
echo "<td nowrap STYLE='background-color:#FFF9C4'>Klax</td>";
echo "<td nowrap STYLE='background-color:#FFF9C4'>Spanien</td>";
echo "<td nowrap STYLE='background-color:#FFF9C4'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF9C4'>40</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>3</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Peuta W</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Spanien</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>34</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>4</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Artus</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Deutschland</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>-</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>32</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>5</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Viet</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Deutschland</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>-</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>31</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>5</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Seri</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Deutschland</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>31</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>6</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Peuta S</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Brasilien</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>30</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>7</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Oleg</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Portugal</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>29</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>7</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Willy</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Niederlande</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>-</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>29</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>8</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>David</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Niederlande</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>28</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>8</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Eppi</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>England</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>28</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>9</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Bris</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Niederlande</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>-</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>22</td>";
echo "</tr>";
echo "<tr STYLE='text-align:center'>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>10</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>HonZ</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>Frankreich</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>bezahlt</td>";
echo "<td nowrap STYLE='background-color:#FFF5F5'>20</td>";
echo "</tr>";
echo "</table>";
echo "</td>";
echo "<td nowrap width='200' align='right'><img src='http://www.pewei.de/wp-content/uploads/2012/05/wm2010.png' alt='WM 2010'></td>";
echo "</tr>";
echo "</table>";

echo "<br>";

echo "<table width='1450' border='1' cellspacing='1' cellpadding='1'>";
echo "<tr>";
echo "<th nowrap colspan='29'>";
echo "<h2>Absolvierte Spiele</h2>";
echo "</th>";
echo "</tr>";
echo "<tr bgcolor='#FF9933'>";
echo "<th nowrap width='80' rowspan='2'>Gruppe</th>";
echo "<th nowrap width='250' rowspan='2'>Begegnung</th>";
echo "<th nowrap width='80' rowspan='2'>Ergebnis</th>";
echo "<th nowrap width='80' colspan='2'>HonZ</th>";
echo "<th nowrap width='80' colspan='2'>Viet</th>";
echo "<th nowrap width='80' colspan='2'>Seri</th>";
echo "<th nowrap width='80' colspan='2'>Peuta S</th>";
echo "<th nowrap width='80' colspan='2'>David</th>";
echo "<th nowrap width='80' colspan='2'>Peuta W</th>";
echo "<th nowrap width='80' colspan='2'>Eppi</th>";
echo "<th nowrap width='80' colspan='2'>Bris</th>";
echo "<th nowrap width='80' colspan='2'>Eugen</th>";
echo "<th nowrap width='80' colspan='2'>Oleg</th>";
echo "<th nowrap width='80' colspan='2'>Klax</th>";
echo "<th nowrap width='80' colspan='2'>Willy</th>";
echo "<th nowrap width='80' colspan='2'>Artus</th>";
echo "</tr>";
echo "<tr bgcolor='#FF9933'>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "<th nowrap width='60'>Tipp</th>";
echo "<th nowrap width='20'>P</th>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>A</td>";
echo "<td nowrap>Südafrika-Mexiko</td>";
echo "<td nowrap>1-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>A</td>";
echo "<td nowrap>Uruguay-Frankreich</td>";
echo "<td nowrap>0-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>B</td>";
echo "<td nowrap>Südkorea-Griechenland</td>";
echo "<td nowrap>2-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>B</td>";
echo "<td nowrap>Argentinien-Nigeria</td>";
echo "<td nowrap>1-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>3-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>C</td>";
echo "<td nowrap>England-USA</td>";
echo "<td nowrap>1-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>4-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>C</td>";
echo "<td nowrap>Algerien-Slowenien</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>D</td>";
echo "<td nowrap>Serbien-Ghana</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>D</td>";
echo "<td nowrap>Deutschland-Australien</td>";
echo "<td nowrap>4-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>4-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>E</td>";
echo "<td nowrap>Niederlande-Dänemark</td>";
echo "<td nowrap>2-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>E</td>";
echo "<td nowrap>Japan-Kamerun</td>";
echo "<td nowrap>1-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-4</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>F</td>";
echo "<td nowrap>Italien-Paraguay</td>";
echo "<td nowrap>1-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>F</td>";
echo "<td nowrap>Neuseeland-Slowakei</td>";
echo "<td nowrap>1-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>0-4</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>G</td>";
echo "<td nowrap>Elfenbeinküste-Portugal</td>";
echo "<td nowrap>0-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-5</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>G</td>";
echo "<td nowrap>Brasilien-Nordkorea</td>";
echo "<td nowrap>2-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>5-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>H</td>";
echo "<td nowrap>Honduras-Chile</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-4</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>H</td>";
echo "<td nowrap>Spanien-Schweiz</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>A</td>";
echo "<td nowrap>Südafrika-Uruguay</td>";
echo "<td nowrap>0-3</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>B</td>";
echo "<td nowrap>Argentinien-Südkorea</td>";
echo "<td nowrap>4-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>B</td>";
echo "<td nowrap>Griechenland-Nigeria</td>";
echo "<td nowrap>2-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>A</td>";
echo "<td nowrap>Frankreich-Mexiko</td>";
echo "<td nowrap>0-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>D</td>";
echo "<td nowrap>Deutschland-Serbien</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>3-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>C</td>";
echo "<td nowrap>Slowenien-USA</td>";
echo "<td nowrap>2-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>C</td>";
echo "<td nowrap>England-Algerien</td>";
echo "<td nowrap>0-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>4-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>4-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>E</td>";
echo "<td nowrap>Niederlande-Japan</td>";
echo "<td nowrap>1-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>D</td>";
echo "<td nowrap>Ghana-Australien</td>";
echo "<td nowrap>1-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>E</td>";
echo "<td nowrap>Kamerun-Dänemark</td>";
echo "<td nowrap>1-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>F</td>";
echo "<td nowrap>Slowakei-Paraguay</td>";
echo "<td nowrap>0-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>F</td>";
echo "<td nowrap>Italien-Neuseeland</td>";
echo "<td nowrap>1-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>G</td>";
echo "<td nowrap>Brasilien-Elfenbeinküste</td>";
echo "<td nowrap>3-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>G</td>";
echo "<td nowrap>Portugal-Nordkorea</td>";
echo "<td nowrap>7-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>4-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>H</td>";
echo "<td nowrap>Chile-Schweiz</td>";
echo "<td nowrap>1-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>H</td>";
echo "<td nowrap>Spanien-Honduras</td>";
echo "<td nowrap>2-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>5-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>6-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>4-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>A</td>";
echo "<td nowrap>Frankreich-Südafrika</td>";
echo "<td nowrap>1-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>A</td>";
echo "<td nowrap>Mexiko-Uruguay</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>B</td>";
echo "<td nowrap>Griechenland-Argentinien</td>";
echo "<td nowrap>0-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-4</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>B</td>";
echo "<td nowrap>Nigeria-Südkorea</td>";
echo "<td nowrap>2-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>C</td>";
echo "<td nowrap>Slowenien-England</td>";
echo "<td nowrap>0-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>C</td>";
echo "<td nowrap>USA-Algerien</td>";
echo "<td nowrap>1-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>D</td>";
echo "<td nowrap>Deutschland-Ghana</td>";
echo "<td nowrap>1-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>4-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>3-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>D</td>";
echo "<td nowrap>Australien-Serbien</td>";
echo "<td nowrap>2-1</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-3</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>F</td>";
echo "<td nowrap>Slowakei-Italien</td>";
echo "<td nowrap>3-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-0</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>F</td>";
echo "<td nowrap>Paraguay-Neuseeland</td>";
echo "<td nowrap>0-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>E</td>";
echo "<td nowrap>Kamerun-Niederlande</td>";
echo "<td nowrap>1-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-4</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightblue'>0-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>E</td>";
echo "<td nowrap>Dänemark-Japan</td>";
echo "<td nowrap>1-3</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>0-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>G</td>";
echo "<td nowrap>Portugal-Brasilien</td>";
echo "<td nowrap>0-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-0</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>3-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>G</td>";
echo "<td nowrap>Nordkorea-Elfenbeinküste</td>";
echo "<td nowrap>0-3</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>0-4</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>0-3</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>1-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>H</td>";
echo "<td nowrap>Chile-Spanien</td>";
echo "<td nowrap>1-2</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>0-4</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>0-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>2-4</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>0-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-2</td>";
echo "<td nowrap STYLE='background-color:red; color:white '>3</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>0-3</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>0-2</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "</tr>";
echo "<tr STYLE='background-color:#CCFFFF; text-align:center'>";
echo "<td nowrap>H</td>";
echo "<td nowrap>Schweiz-Honduras</td>";
echo "<td nowrap>0-0</td>";
echo "<td nowrap STYLE='background-color:#00FFFF; text-align:center'>4-2</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#99CCFF'>3-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFCC99'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFFFCC'>2-1</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#C0C0C0'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightgreen'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCFFCC'>3-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#FFDEAD'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:lightblue'>1-1</td>";
echo "<td nowrap STYLE='background-color:green; color:white '>1</td>";
echo "<td nowrap STYLE='background-color:#CCFFFF'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:#CCCCFF'>2-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "<td nowrap STYLE='background-color:lightyellow'>1-0</td>";
echo "<td nowrap STYLE='background-color:yellow'>0</td>";
echo "</tr>";
echo "</table>";
}
else
{
    echo "<h2><b>Du kommst hier net rein!!</b></h2>";
}
?>